### ISSUE TITLE
MixPanel Events for tracking Security Upgrade pass rate

### ISSUE THREAD

**Issue by benmoranpm** [vechain/veworld-mobile#2320]
To track the successful completion of the security upgrade, we can add in some mix panel events so we can track once the release is made. 

- [x] If possible, the events we track should only be registered if the flow completes and wallets/accounts are all available after a user upgrades. 
- [x] We should be able to see # of attempts vs # of success. If not then we can see # of installs, but a user may not immediately got through the flow. 
- [ ] A back up build we can upload to App Store and playstore if we see issues.
